version = 1

[envs.numpydoc]
channels = ["conda-forge"]
dependencies = { numpydoc = "*" }
exposed = { numpydoc = "numpydoc" }

[envs.pixi-diff]
channels = ["conda-forge"]
dependencies = { pixi-diff = "*" }
exposed = { pixi-diff = "pixi-diff" }

[envs.pixi-diff-to-markdown]
channels = ["conda-forge"]
dependencies = { pixi-diff-to-markdown = "*" }
exposed = { pixi-diff-to-markdown = "pixi-diff-to-markdown" }

[envs.tldr]
channels = ["conda-forge"]
dependencies = { tldr = "*" }
exposed = { tldr = "tldr" }

[envs.pixi-browse]
channels = ["conda-forge"]
dependencies = { pixi-browse = "*" }
exposed = { pixi-browse = "pixi-browse" }

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.pixi-gui]
channels = ["https://prefix.dev/pixi-gui", "https://prefix.dev/conda-forge"]
dependencies = { pixi-gui = "*" }
exposed = { pixi-gui = "pixi-gui" }
shortcuts = ["pixi-gui"]

[envs.jujutsu]
channels = ["conda-forge"]
dependencies = { jujutsu = "==0.39.0" }
exposed = { jj = "jj" }

[envs.zizmor]
channels = ["conda-forge"]
dependencies = { zizmor = "*" }
exposed = { zizmor = "zizmor" }

[envs.git]
channels = ["conda-forge"]
dependencies = { git = "==2.51.0" }
exposed = { git = "git", git-cvsserver = "git-cvsserver", git-receive-pack = "git-receive-pack", git-shell = "git-shell", git-upload-archive = "git-upload-archive", git-upload-pack = "git-upload-pack", gitk = "gitk", scalar = "scalar" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }

[envs.zoxide]
channels = ["conda-forge"]
dependencies = { zoxide = "*" }
exposed = { zoxide = "zoxide" }

[envs.starship]
channels = ["conda-forge"]
dependencies = { starship = "*" }
exposed = { starship = "starship" }

[envs.python]
channels = ["conda-forge"]
dependencies = { python = "==3.13" }
exposed = { idle3 = "idle3", "idle3.13" = "idle3.13", pydoc = "pydoc", pydoc3 = "pydoc3", "pydoc3.13" = "pydoc3.13", python = "python", python3 = "python3", python3-config = "python3-config", "python3.1" = "python3.1", "python3.13" = "python3.13", "python3.13-config" = "python3.13-config" }

[envs.yt-dlp]
channels = ["conda-forge"]
dependencies = { yt-dlp = "*" }
exposed = { yt-dlp = "yt-dlp" }

[envs.lefthook]
channels = ["conda-forge"]
dependencies = { lefthook = "*" }
exposed = { lefthook = "lefthook" }

[envs.prek]
channels = ["conda-forge"]
dependencies = { prek = "*" }
exposed = { prek = "prek" }

[envs.yq]
channels = ["conda-forge"]
dependencies = { yq = "*" }
exposed = { tomlq = "tomlq", yq = "yq", xq = "xq" }

[envs.jq]
channels = ["conda-forge"]
dependencies = { jq = "*" }
exposed = { jq = "jq" }

[envs.carapace]
channels = ["conda-forge"]
dependencies = { carapace = "*" }
exposed = { carapace = "carapace" }
